### ISSUE TITLE
btd6rogue mod

### ISSUE THREAD

**Issue by MommaBear091992** [mend-dev/BTD6Rogue#1]
i was using the btd6rogue mod the past week and it worked great. i updated it last night & now the mod wont show up at the start of each round. how do i get it working again?

**Comment by mend-dev** [comment]
BTD6 Rogue now has it's own gamemode

(in the future, you'll be able to select things like chimps, X towers only, etc) But for the sake of having it in the code now,

it's under the Hard gamemodes

**Comment by MommaBear091992** [comment]
Oh thank you so much

**Comment by MommaBear091992** [comment]
Do you know why it keeps doing this every so often? Then I have to restart
because I can't do anything else.

**Comment by wolfyplay** [comment]
> BTD6 Rogue now has it's own gamemode
> 
> (in the future, you'll be able to select things like chimps, X towers only, etc) But for the sake of having it in the code now,
> 
> it's under the Hard gamemodes

i tried joining chimps and hard and it didnt work, and when i click that button it shows no mods
