### ISSUE TITLE
Idk how to install it on my btd6

### ISSUE THREAD

**Issue by QvMain** [mend-dev/BTD6Rogue#10]
Can u pls help me on where t put the file

**Comment by mend-dev** [comment]
After installing Melonloader you should have a mods folder in your BTD6 folder
Just throw it in the mods folder like any other mod

Heres a tutorial:
https://www.youtube.com/watch?v=AuqsEx7e3bM&ab_channel=Tewtiy

**Comment by Sylvie44444** [comment]
does that tutorial also work for the Epic games version of BTD6?

(have it on Steam as well but prefer to have a seperate instance for modding it)

**Comment by rocko2314243** [comment]
> does that tutorial also work for the Epic games version of BTD6?
> 
> (have it on Steam as well but prefer to have a seperate instance for modding it)

BTD6 Epic Games compat by GrahamKracker
