### ISSUE TITLE
The mod for me for some reason just is not working for me like at all

### ISSUE THREAD

**Issue by miah50106** [mend-dev/BTD6Rogue#14]
So basically I use melon loader and when I open up the game everything works but when I try to play the Roguelike mode it would just show up like a normal game of btd6 with all the monkeys and everything It doesnt have a pop up for the heroes or monkeys its like your playing a regular game.

**Comment by Zoomycow** [comment]
I have the same issue aswell.

**Comment by DilfHunter696** [comment]
Still running into this 3 weeks later. Any chance this is still alive and possibly fixed? Would love to check this out.

**Comment by monster0607nat** [comment]
nope
