### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by CO0LM** [mend-dev/BTD6Rogue#18]
It doesn't load, but I think I have found the solution - it doesn't have a .dll file. All my other mods have one, that is my guess. Hope it helps!!!

**Comment by mend-dev** [comment]
the .dll is the mod, if you dont have it, you dont have it installed
check your mods in game, if it shows BTD6Rogue there then its bug, otherwise you can install through the releases page on the repo or through the mod browser :D
